# Generated by Django 5.1.6 on 2025-02-17 20:57

import javiera.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteArtigosTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigos_titulo', models.TextField()),
                ('artigos_descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponenteContatoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_titulo', models.TextField()),
                ('contato_descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InicioBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducao', models.ImageField(upload_to='javiera/cms/inicio')),
                ('artigos', models.ImageField(upload_to='javiera/cms/inicio')),
            ],
            options={
                'abstract': False,
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InicioImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.ImageField(upload_to='javiera/cms/inicio')),
            ],
            options={
                'abstract': False,
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InicioTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducao_titulo', models.TextField()),
                ('introducao_subtitulo', models.TextField()),
                ('sobre_titulo', models.TextField()),
                ('sobre_descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SobreImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_1', models.ImageField(upload_to='javiera/cms/sobre')),
                ('imagem_2', models.ImageField(upload_to='javiera/cms/sobre')),
            ],
            options={
                'abstract': False,
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SobreTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('paragrafo_1', models.TextField()),
                ('paragrafo_2', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
