# Generated by Django 5.1.6 on 2025-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0004_componentecontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicio',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='javiera/cms/inicio'),
        ),
    ]
