# Generated by Django 5.1.6 on 2025-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0005_paginainicio_imagem1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicio',
            name='bg1',
            field=models.ImageField(blank=True, null=True, upload_to='javiera/cms/inicio'),
        ),
        migrations.AddField(
            model_name='paginainicio',
            name='bg2',
            field=models.ImageField(blank=True, null=True, upload_to='javiera/cms/inicio'),
        ),
    ]
