# Generated by Django 5.1.6 on 2025-02-19 17:09

import javiera.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0006_paginainicio_bg1_paginainicio_bg2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('paragrafo1', models.TextField()),
                ('paragrafo2', models.TextField()),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='javiera/cms/sobre')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='javiera/cms/sobre')),
            ],
            options={
                'abstract': False,
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
    ]
