# Generated by Django 5.1.6 on 2025-02-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0007_paginasobre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponenteArtigosTexto',
        ),
        migrations.DeleteModel(
            name='ComponenteContatoTexto',
        ),
        migrations.DeleteModel(
            name='InicioBg',
        ),
        migrations.DeleteModel(
            name='InicioImg',
        ),
        migrations.DeleteModel(
            name='InicioTexto',
        ),
        migrations.DeleteModel(
            name='SobreImg',
        ),
        migrations.DeleteModel(
            name='SobreTexto',
        ),
    ]
