# Generated by Django 5.1.6 on 2025-10-22 18:42

import django.db.models.deletion
import javiera.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('javiera', '0008_delete_componenteartigostexto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='javiera/cursos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Artigo (Quill.js)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='javiera/aulas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='javiera.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
            bases=(javiera.mixins.DeleteOldImageMixin, models.Model),
        ),
    ]
