# Generated by Django 5.1.6 on 2025-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecta',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/inicio'),
        ),
        migrations.AlterField(
            model_name='paginainicio',
            name='bg1',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/inicio'),
        ),
        migrations.AlterField(
            model_name='paginainicio',
            name='bg2',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/inicio'),
        ),
        migrations.AlterField(
            model_name='paginaservicos',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/inicio'),
        ),
    ]
