# Generated by Django 5.1.6 on 2025-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0002_alter_componentecta_bg_alter_paginainicio_bg1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicio',
            name='processo4Texto',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paginainicio',
            name='processo4Titulo',
            field=models.TextField(default='öi'),
            preserve_default=False,
        ),
    ]
