# Generated by Django 5.1.6 on 2025-05-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0003_paginainicio_processo4texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecta',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/cta'),
        ),
        migrations.AlterField(
            model_name='paginaservicos',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/servicos'),
        ),
        migrations.AlterField(
            model_name='paginasobre',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/cms/sobre'),
        ),
    ]
