# Generated by Django 5.1.6 on 2025-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0004_alter_componentecta_bg_alter_paginaservicos_bg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentecta',
            old_name='bg',
            new_name='bg1',
        ),
        migrations.RenameField(
            model_name='paginaservicos',
            old_name='bg',
            new_name='bg1',
        ),
    ]
