# Generated by Django 5.1.6 on 2025-05-17 19:15

import francoadv.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0005_rename_bg_componentecta_bg1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='francoadv/cms/servico')),
            ],
            bases=(francoadv.mixins.DeleteOldImageMixin, models.Model),
        ),
    ]
