# Generated by Django 5.1.6 on 2025-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francoadv', '0007_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='francoadv/blog'),
        ),
    ]
